[tool.poetry]
name = "poetry-dockerize-plugin"
version = "0.1.0"
description = "Package your Poetry application to a Docker image automatically."
authors = ["Nicolò Boschi <boschi1997@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "poetry_dockerize_plugin", from = "."}
]


[tool.poetry.plugins."poetry.application.plugin"]
dockerize = "poetry_dockerize_plugin.plugin:DockerApplicationPlugin"

[tool.poetry.dependencies]
python = "^3.9"
poetry = "^1.7.1"
poetry-core = "^1.8.1"
docker = "^6.1.3"
pytest = "^7.4.4"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
